Fix vfssimple factory
C2FO/vfs pull request #106
Opened 2021-11-28 22:05 UTC by funkyshu

fixes #97 
- fixed azure helper func for vfssimple, ensuring it works on File URIs in addition to Location URIs
- fixed by updating vfssimple logic to ensure the most specific registered backend that matches a url is used, not just the first one it comes across.  Updated vfssimple docs.
- Added vfssimple tests.  Zero to 100% coverage.

2021-11-28 22:07 UTC, funkyshu commented on backend/azure/fileSystem.go
>  }
No real logic change here.  Just made `EnsureTrailingSlash` conditional since this func will be used for file URIs too.

2021-11-30 14:57 UTC, dmcilvain44 approved these changes

2021-12-01 22:39 UTC, seeroush requested changes
just a minor nit, but otherwise 👍

2021-12-01 22:39 UTC, seeroush commented on vfssimple/vfssimple.go
> +	if authority == "" && !(scheme == "file" || scheme == "mem") {
These should probably reference the constants in each of the supplied backends:

`backend.os.Scheme` and `backends.mem.Scheme`

2021-12-01 22:52 UTC, seeroush approved these changes

2021-12-02 06:22 UTC, merged