Version deletes az
C2FO/vfs pull request #121
Opened 2022-06-30 19:15 UTC by dhondgepooja

2022-06-30 20:49 UTC, dhondgepooja commented on backend/azure/client.go
For this file, we don't have any unit tests so used the integration tests to run through each setting and have shared the verification details internally.

2022-07-02 07:45 UTC, funkyshu requested changes

2022-07-05 15:06 UTC, juanri0s approved these changes

2022-07-06 13:43 UTC, AndrewKileC2FO approved these changes

2022-07-06 14:20 UTC, dhondgepooja commented on backend/azure/file.go
> +		default:
I was getting lint errors since I had only one switch case. But couldn't convert it to 'if clause' since checking type is easier with switch case.

2022-07-06 14:24 UTC, dhondgepooja commented on backend/azure/file.go
> +	}
Updated this to now perform normal deletes first before deleting versions. https://github.com/C2FO/vfs/pull/121/commits/7ceb99b887f8841ead55ea24455f8bc09063e325#diff-c9a3c95aca12f12da685d4d9b6dba52a4466c50211c30534a676bf38846b76dfR219

2022-07-06 18:36 UTC, jkware approved these changes

2022-07-07 15:09 UTC, dmcilvain44 approved these changes

2022-07-07 15:43 UTC, dhondgepooja commented
@funkyshu this is ready for another review whenever you have a chance.

2022-07-08 15:09 UTC, funkyshu approved these changes

2022-07-08 15:11 UTC, merged