Improved Windows support
C2FO/vfs pull request #207
Opened 2024-10-17 11:02 UTC by NathanBaulch

This doesn't 100% fix all issues on Windows (mostly in the `os` filesystem) but it gets the project closer.

2024-11-17 19:13 UTC, funkyshu requested changes
This looks good to me. Just add a CHANGELOG.md entry.
Also can you add `windows-latest` to the test matrix at https://github.com/C2FO/vfs/blob/main/.github/workflows/go.yml#L17

2024-11-17 21:25 UTC, NathanBaulch commented
Unit tests all pass on my Windows 10 machine - I guess we have more work to do to get it running in GitHub actions...

2025-01-06 05:30 UTC, funkyshu approved these changes

2025-01-06 05:31 UTC, merged

2025-01-06 05:32 UTC, funkyshu commented
@NathanBaulch This is a set of fixes I've meant to address for a long time but never had time for since we don't use Windows.  Thanks for this important fix.