add support for assumed role credentials in the s3 backend
C2FO/vfs pull request #219
Opened 2024-12-23 23:09 UTC by grant-higgins-0

2024-12-26 21:28 UTC, funkyshu requested changes
This looks good but can you be sure to update the docs?

2024-12-27 18:04 UTC, funkyshu requested changes

2024-12-27 18:04 UTC, funkyshu commented on docs/s3.md
> +    ACL                         string `json:"acl,omitempty"`
use tabs, not spaces here for consistency.

2024-12-27 18:04 UTC, funkyshu approved these changes

2025-01-15 13:31 UTC, dustin-schnee approved these changes

2025-01-15 15:44 UTC, merged