Add support of key exchange algorithm as an option
C2FO/vfs pull request #81
Opened 2021-07-20 11:29 UTC by atulbhadouria

2021-07-20 11:47 UTC, vikram-c2fo approved these changes

2021-07-20 15:29 UTC, funkyshu requested changes
This looks good.  Can you update https://github.com/C2FO/vfs/blob/master/docs/sftp.md#type-options to reflect the change in the Options struct?
Can you also update the Unreleased sectionof https://github.com/C2FO/vfs/blob/master/CHANGELOG.md .  This change would fall under an `Added` section.

2021-07-21 14:54 UTC, Roosh513 approved these changes

2021-07-23 16:26 UTC, funkyshu approved these changes

2021-07-23 16:26 UTC, merged